# Generated by Django 4.1.3 on 2022-12-05 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0004_remove_group_pets"),
        ("pets", "0003_remove_pet_traits"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pets",
                to="groups.group",
            ),
        ),
    ]
