# Generated by Django 4.1.3 on 2022-12-05 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0003_alter_group_pets"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group",
            name="pets",
        ),
    ]
